# Generated by Django 5.0 on 2024-03-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name': 'News Letters', 'verbose_name_plural': 'News Letters'},
        ),
    ]
