version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ConnectEdu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@blo 2003
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .

    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    environment:
      DB_HOST: db
      DB_NAME: ConnectEdu
      DB_USER: postgres
      DB_PASSWORD: P@blo 2003
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

    volumes:
      - .:/app

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest

  celery:
    restart: always
    image: connectedu-web
    command: celery -A connectedu worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

    environment:
      DB_HOST: db
      DB_NAME: ConnectEdu
      DB_USER: postgres
      DB_PASSWORD: P@blo 2003
    # entrypoint: /app/entrypoint.sh

volumes:
  db_data:
