# Generated by Django 5.0 on 2024-02-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ecole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleves',
            old_name='titeur',
            new_name='tuteur',
        ),
        migrations.RenameField(
            model_name='professeurs',
            old_name='telefone',
            new_name='telephone',
        ),
    ]
