# Generated by Django 5.0 on 2024-02-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ecole', '0003_alter_parents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='professeurs',
            name='matricule',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
