# Generated by Django 5.0 on 2024-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ecole', '0002_rename_titeur_eleves_tuteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
