# Generated by Django 5.0 on 2024-04-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes_ecole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoles',
            old_name='email',
            new_name='email_ecole',
        ),
    ]
