# Generated by Django 5.0 on 2024-04-24 21:47

import comptes_ecole.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes_ecole', '0002_rename_email_ecoles_email_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoles',
            name='document',
            field=models.FileField(blank=True, upload_to=comptes_ecole.models.upload_to),
        ),
        migrations.AlterField(
            model_name='ecoles',
            name='logo',
            field=models.ImageField(blank=True, upload_to=comptes_ecole.models.upload_to),
        ),
    ]
