# Generated by Django 5.0 on 2024-04-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ecole_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidutemps',
            name='professeur',
        ),
    ]
